# -*- coding: utf-8 -*-
"""BRAIN_TUMOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BvrCdd7RCyyIRTaAjtCqDyv36Sl_RrF
"""

import streamlit as st
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image

# Import Libraries
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Conv2D

from tensorflow.keras.layers import MaxPooling2D

from tensorflow.keras.layers import Flatten

from tensorflow.keras.layers import Dense

from tensorflow.keras.layers import Dropout

import matplotlib.pyplot as plt

import numpy as np

# Data Preprocessing
# Image Augmentation
train_datagen = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    zoom_range=0.2,

    horizontal_flip=True,

    validation_split=0.2

)

# Mount the Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define Paths
train_path = "/content/drive/MyDrive/Brain_Tumor/Training"
test_path = "/content/drive/MyDrive/Brain_Tumor/Testing"

# Create ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

# Training Generator
train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

#Validation Generator
validation_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="validation"
)

#Test Generator(used after training)
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    test_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

import os

print(os.listdir("/content/drive/MyDrive/Brain_Tumor"))
print(os.listdir(train_path))

# Load Dataset
train_generator = train_datagen.flow_from_directory(

    train_path,

    target_size=(224,224),

    batch_size=32,

    class_mode="categorical",

    subset="training"

)

validation_generator = train_datagen.flow_from_directory(

    test_path,

    target_size=(224,224),

    batch_size=32,

    class_mode="categorical",

    subset="validation"

)

# ckeck classes
print(train_generator.class_indices)

# CNN Model
# Build CNN
model = Sequential()

model.add(

Conv2D(

32,

(3,3),

activation="relu",

input_shape=(224,224,3)

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(

Conv2D(

64,

(3,3),

activation="relu"

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(

Conv2D(

128,

(3,3),

activation="relu"

)

)

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(128,activation="relu"))

model.add(Dropout(0.5))

model.add(Dense(4,activation="softmax"))

# Model Summary
model.summary()

# Model Compilation
# Compile
model.compile(

optimizer="adam",

loss="categorical_crossentropy",

metrics=["accuracy"]

)

# Model Training
# Train
history = model.fit(

train_generator,

epochs=10,

validation_data=validation_generator

)

# Performance
# Plot Accuracy
plt.plot(history.history["accuracy"])

plt.plot(history.history["val_accuracy"])

plt.legend(["Train","Validation"])

plt.show()

# Plot LOss
plt.plot(history.history["loss"])

plt.plot(history.history["val_loss"])

plt.legend(["Train","Validation"])

plt.show()

# Evaluate
loss,accuracy=model.evaluate(validation_generator)

print(accuracy)

# Save Model
model.save("brain_tumor_model.keras")

# Prediction
# Load Model
from tensorflow.keras.models import load_model

model=load_model("brain_tumor_model.keras")

from tensorflow.keras.preprocessing import image

# NOTE: The original error was FileNotFoundError because the image 'Multiple-Views-Of-Brain-MRI-Results-1024x499.webp'
# was not found directly in the 'Training' folder. Your images are likely in subdirectories
# like 'glioma', 'meningioma', 'notumor', 'pituitary' within the Training folder.
# You need to provide the correct path to an actual image file from one of those subfolders.
# For example, if you have an image 'image_0001.jpg' in the 'glioma' folder, the path would be:
# "/content/drive/MyDrive/Brain_Tumor/Training/glioma/image_0001.jpg"

# Please replace the placeholder path below with the actual path to an image file from your dataset.
img = image.load_img(
    "/content/drive/MyDrive/Brain_Tumor/Training/glioma/Tr-gl_1387.jpg", # Updated with a valid image name
    target_size=(224, 224)
)

img = image.img_to_array(img)
img = img / 255

import os

# List files in the 'glioma' directory to find an actual image file name
print(os.listdir('/content/drive/MyDrive/Brain_Tumor/Training/glioma'))

# Prediction
import numpy as np

# Expand dimensions to create a batch of 1 image
img_batch = np.expand_dims(img, axis=0)
prediction = model.predict(img_batch)

classes=["Glioma",
"Meningioma",
"No Tumor",
"Pituitary"]

print(classes[np.argmax(prediction)])

# Upload MRI
import streamlit as st

uploaded_file = st.file_uploader(

"Upload MRI",

type=["jpg","png","jpeg"]

)

# Display Image
# Predict
if st.button("Predict"):

    prediction=model.predict(img)

    st.success(

    classes[np.argmax(prediction)]

    )

# Confidence
confidence=np.max(prediction)*100

st.write(

f"Confidence : {confidence:.2f}%"

)

